@echo off
echo Starting Real Estate Analytics Platform...
echo.
echo Activating virtual environment...
call venv\Scripts\activate
echo.
echo Installing dependencies...
pip install -r requirements.txt
echo.
echo Starting Streamlit application...
streamlit run app/Home.py
pause
